# Generated by Django 3.2 on 2021-04-19 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210418_0055'),
        ('endoscopies', '0005_remove_endoscopy_id_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='endoscopy',
            name='id_exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
    ]
