# Generated by Django 3.2 on 2021-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endoscopies', '0006_endoscopy_id_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='endoscopies/%Y/%m/%d'),
        ),
    ]
